services:
  api:                       # FastAPI 서버
    build: ./app/api      
    ports:
      - "8000:8000"
    
    depends_on:
      - db
      - redis
    volumes:
      - ./app/api:/app

# hub.docker.com/_/mysql#environment-variables -> 환경 키 설정 방법
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
    ports:
      - "33061:3306"
    volumes:
      - local_db:/var/lib/mysql

  worker:
    build: ./app/worker
    volumes:
      - ./app/worker:/app
    depends_on:
      - redis
  
  redis:
    image: redis:7


volumes:
  local_db:
